# file: kịch_bản/kho_kich_ban_sinh_vien.py

SCENARIOS_SINH_VIEN = {
    "morning": [
        "Morning cả nhà, ae sao rồi? Em làm ly cafe rồi chuẩn bị lên lớp đây, có kèo nào hóng với nhé!",
        "Hello mọi người, đêm qua em thức cày chart hơi mệt mà sáng vào nhóm thấy có tín hiệu đẹp là tỉnh ngủ hẳn.",
        "Chào ngày mới! Em thì vẫn quan điểm cũ, phải chia trứng nhiều giỏ, một ít coin, ít chứng, còn lại thì theo ae ở đây.",
        "Sáng nay có môn Triết chán quá, chắc em lại ngồi cuối lớp hóng nhóm mình thôi. Mọi người có gì cập nhật nhé!",
        "Vào nhẹ một lệnh đầu ngày lấy vía may mắn nào. Chúc cả nhà mình hôm nay rực rỡ nhé!",
        "Mấy đứa bạn cùng phòng còn đang ngáy o o, chúng nó đâu biết mình đã dậy sớm 'làm kinh tế'. Haha.",
        "Admin với mọi người phân tích hay thật, em thấy nó logic hơn khối môn em đang học. Nay có gì hay không admin ơi?",
        "Hello ae, khởi đầu ngày mới bằng một lệnh win thì còn gì bằng. Cả nhà ổn cả chứ?",
        "Deadline dí tới nơi rồi mà vẫn không bỏ được thói quen vào hóng nhóm. Cơ hội kiếm tiền sao bỏ lỡ được.",
        "Làm một tay là có tiền gia hạn 4G cả tháng rồi. Mọi người có kèo nào thơm không, chia sẻ em với!",
        "Alo alo, cả nhà ăn sáng chưa? Em đang tính kiếm tiền bát phở đặc biệt từ nhóm mình đây.",
        "Em lướt mấy group tài chính rồi mà thấy không đâu thực chiến như nhóm mình. Hôm nay mình chiến gì đây ae?",
        "Kiến thức trong sách vở đôi khi cũ quá, phải học kinh nghiệm thực tế ở đây mới nhanh giàu được.",
        "Sáng nay thầy điểm danh đột xuất, hú hồn chim én. Giờ mới thở phào vào với mọi người được đây.",
        "Hello, có ai ở đây không? Người trẻ như tụi mình phải chấp nhận rủi ro mới mong bứt phá được, đúng không cả nhà?",
        "Vừa vào lệnh xong là phải tắt thông báo để tập trung nghe giảng đây. Hóng kết quả từ mọi người nhé!",
        "Cảm giác 30 phút sau vào thấy lệnh win nó sướng hơn cả được điểm A ấy mọi người ạ.",
        "Em đang ngồi quán cafe gần trường làm bài tập, nhưng tay vẫn cầm điện thoại hóng kèo. Có ai giống em không?",
        "Luôn tự nhủ phải có kỷ luật thép, thắng không kiêu bại không nản. Ae cùng cố gắng nhé!",
        "Mở bát buổi sáng thành công rực rỡ! Hôm nay chắc là một ngày may mắn đây. Cảm ơn admin nhiều."
    ],
    "noon": [
        "Trưa rồi, mọi người nghỉ ngơi chưa? Em vừa tan học là phải vào check nhóm ngay, sợ lỡ kèo.",
        "Trưa nay cả phòng rủ đi ăn lẩu, em đang tính làm một tay kiếm tiền bao cả bọn đây. Có kèo nào không admin ơi?",
        "Ngồi canteen trường vừa ăn cơm vừa soi kèo, cảm giác còn hồi hộp hơn chờ điểm thi. Cả nhà sao rồi?",
        "Em vừa nạp thêm ít vốn, tiền lời con coin hôm trước. Phải biết xoay vòng vốn hợp lý, mọi người nhỉ?",
        "Nhiều người ngoài nhìn vào cứ nghĩ đây là đỏ đen, nhưng chỉ anh em mình mới hiểu nó là game của xác suất và tâm lý.",
        "Húp nhẹ kèo buổi trưa là chiều có tiền dẫn gấu đi xem phim rồi. Cảm ơn các cao nhân.",
        "Em thích kiểu kiếm tiền nhanh gọn này, hợp với tuổi trẻ. Chứ làm thêm mấy chỗ khác mệt lắm.",
        "Lại thắng rồi! Có thêm tiền để mua mấy khóa học online rồi. Phải luôn đầu tư cho bản thân, đúng không cả nhà?",
        "Trời nắng quá, em đang ngồi thư viện cho mát, vừa học vừa hóng kèo đây. Nhóm mình có ai ở Hà Nội không?",
        "Vừa chợp mắt tí dậy đã thấy nhóm báo tin vui, tỉnh cả ngủ. Chúc mừng mọi người nhé.",
        "Cơm sinh viên đạm bạc thôi, nhưng nhờ có nhóm mà nay em gọi thêm được ly trà sữa full topping. Haha.",
        "Cảm giác tự chủ tài chính thích thật mọi người ạ. Không phải ngửa tay xin tiền phụ huynh nữa.",
        "Em đang xem lại mấy lệnh thua buổi sáng để rút kinh nghiệm. Có ai có kinh nghiệm gì chia sẻ em với.",
        "Hello, có ai đang canh không? Chơi cái này phải giữ cái đầu lạnh, không được cay cú.",
        "Bạn em làm thêm được có 20k/giờ, nghĩ mà thương. Thấy lựa chọn của mình đúng đắn ghê.",
        "Lại một bữa trưa ấm no. Cảm ơn các admin và mọi người đã kéo em về bờ.",
        "Em chuẩn bị vào học chiều, chúc ae ở lại chiến đấu thắng lợi nhé. Tối em vào tổng kết sau.",
        "Tiền lời hôm nay đủ đóng tiền nhà tháng tới rồi, nhẹ cả người. Vui quá ae ơi!",
        "Tuyệt vời! Chúng ta lại thành công rồi. Chúc mừng cả nhà."
    ],
    "evening": [
        "Tối rồi, sau một ngày học căng thẳng vào nhóm xả stress là tuyệt nhất. Mọi người ăn tối chưa?",
        "Em vừa đi tập gym về, đầu óc minh mẫn hẳn. Giờ là lúc tập trung 'làm kinh tế' đêm khuya.",
        "Càng về đêm càng phải tập trung, soi kèo cũng phải kỹ hơn. Có ai đang soi cùng em không?",
        "Em đang tổng kết lại các lệnh trong ngày. Kỷ luật vẫn là quan trọng nhất, mọi người công nhận không?",
        "Bạn cùng phòng ngủ rồi, giờ là thế giới của riêng em với nhóm mình. Chiến tới đâu đây ae ơi?",
        "Chốt sổ hôm nay lời hơn cả tháng lương làm thêm của bạn em. Đúng là lựa chọn quan trọng hơn nỗ lực.",
        "Chắc em nghỉ sớm mai còn có sức chiến tiếp. Chúc các anh em ở lại gặt hái thêm nhiều thành công nhé!",
        "Cảm ơn cả nhà đã tạo nên một buổi tối rực rỡ. Hôm nay ấm no quá.",
        "Vừa chiến xong trận game, giờ quay lại chiến với ae đây. Tình hình sao rồi mọi người?",
        "Tối nay mà thắng lớn là mai em xin nghỉ học một bữa đi xả hơi. Haha.",
        "Gấu em đang giận vì em mải xem điện thoại. Phải thắng kèo này để mua quà dỗ mới được, ae giúp em!",
        "Em đang bật cả laptop lên để xem chart cho rõ đây. Có ai phân tích kỹ thuật với em không?",
        "Càng về đêm tâm lý càng phải vững. Lỡ thua cũng không được vội vàng gỡ gạc nhé mọi người.",
        "Hello, có kèo nào đêm muộn không admin? Em vẫn đang tràn đầy năng lượng.",
        "Không có gì vui bằng tài khoản nhảy số lúc nửa đêm. Cảm ơn nhóm mình nhiều.",
        "Em đặt mục tiêu mỗi tuần tăng 15% tài khoản. Phải có mục tiêu rõ ràng mới có động lực.",
        "Thôi em chốt ngày ở đây. Dù thắng hay thua thì kiến thức học được là vô giá.",
        "Chúc mọi người ngủ ngon, mơ thấy số đẹp nhé. Em đi ngủ đây.",
        "Lại một đêm khó ngủ vì quá vui. Cảm ơn sự dẫn dắt của admin.",
        "Em sẽ ghi lại hết kinh nghiệm hôm nay, tích lũy mỗi ngày một ít. Cố lên nào!"
    ],
    "experience_motivation": [
        "Hello mọi người, em tâm sự thật, từ khi vào nhóm, em không còn phải xin tiền tiêu vặt của gia đình nữa.",
        "Em mới tự mua được con Macbook mới bằng tiền kiếm được ở đây. Cảm giác nó đã lắm mọi người ạ.",
        "Kiến thức về quản lý vốn ở đây còn quý hơn cả tiền. Em học được nhiều lắm.",
        "Em nghĩ sinh viên như mình nên tiếp xúc với đầu tư sớm, có kinh nghiệm sau này ra đời đỡ bỡ ngỡ.",
        "Mục tiêu của em là ra trường có một số vốn để tự kinh doanh, không phải đi làm thuê.",
        "Khoe thành quả sau một tuần cày cuốc với ae đây. Đủ tiền để em lướt thêm con coin mới rồi.",
        "Ở đây giúp em học được cách giữ bình tĩnh trước biến động, một kỹ năng quá quan trọng.",
        "Giờ em tự tin hơn hẳn khi nói chuyện về tài chính với bạn bè. Cảm thấy mình trưởng thành hơn.",
        "Cảm giác tự mình lo cho cuộc sống mà không cần bố mẹ chu cấp nó tuyệt vời lắm.",
        "Đây không phải là may mắn, đây là kết quả của việc học hỏi và tuân thủ kỷ luật của cả nhóm mình.",
        "Em kéo mấy đứa bạn thân vào đây rồi, hy vọng chúng nó cũng thay đổi được tư duy như em.",
        "Từ một thằng chỉ biết chơi game, giờ em đã biết cách để tiền đẻ ra tiền. Cảm ơn mọi người nhiều.",
        "Em sẽ không bao giờ quên những ngày đầu được các anh trong nhóm chỉ bảo tận tình.",
        "Nhóm mình thực sự uy tín và có tâm, em rất trân trọng điều đó.",
        "Mỗi lần thắng, em đều trích một phần ra tiết kiệm, phải luôn có kế hoạch dự phòng.",
        "Em đang lên kế hoạch đi phượt xuyên Việt bằng tiền mình kiếm được. Nghĩ thôi đã thấy vui.",
        "Va chạm sớm giúp em chín chắn hơn rất nhiều so với bạn bè cùng trang lứa.",
        "Em nhận ra chìa khóa thành công là không ngừng học hỏi và kiên trì. Cảm ơn admin đã truyền cảm hứng.",
        "Cảm ơn nhóm đã cho em cơ hội để bứt phá. Em sẽ luôn đồng hành cùng mọi người.",
        "Em tự hứa sẽ luôn là một thành viên tích cực, cùng xây dựng nhóm mình ngày càng vững mạnh."
    ],
    "interaction": [
        "Admin có thể phân tích sâu hơn về lý do vào lệnh này được không ạ? Em muốn học hỏi thêm.",
        "Em thấy cầu này có vẻ sắp đảo chiều, không biết có ae nào nghĩ giống em không?",
        "Chúc mừng anh X nhé, ngưỡng mộ bản lĩnh của anh quá.",
        "Tay này em thấy hơi khoai nên xin phép ngồi ngoài xem mọi người trổ tài thôi.",
        "Có ai dùng bot hay chỉ báo kỹ thuật nào hay không, chia sẻ cho em với?",
        "Nhóm mình đúng là nơi hội tụ tinh hoa, vào đây em thấy mình thông minh hơn mỗi ngày. Haha.",
        "Cảm ơn anh B đã nhắc nhở, đúng là không nên chủ quan sau khi thắng liên tiếp.",
        "Em vừa vào lệnh theo admin rồi. Giờ ngồi tin tưởng và chờ đợi thôi.",
        "Wow, phân tích của admin đỉnh thật sự, không trượt phát nào. Bái phục!",
        "Mọi người ơi, tay này nên đi bao nhiêu % vốn thì hợp lý nhỉ? Em hơi phân vân.",
        "Lệnh vừa rồi em vào hơi vội, may mà vẫn win. Phải rút kinh nghiệm mới được.",
        "Nhóm mình có ai ở Sài Gòn không ạ? Hôm nào offline giao lưu thì hay quá.",
        "Lại một chiến thắng của cả tập thể. Đoàn kết tạo nên sức mạnh, đúng không cả nhà?",
        "Em vừa đi có việc, giờ mới vào. Có ai tóm tắt giúp em tình hình mấy tay vừa rồi được không ạ?",
        "Em thấy mấy chỉ báo đều đang ủng hộ kèo này. Khá tự tin đấy mọi người.",
        "Mọi người có sách nào hay về tâm lý giao dịch không, giới thiệu em với. Em thấy tâm lý vẫn là yếu nhất.",
        "Tuyệt vời! Thuyền trưởng admin lại đưa chúng ta về bờ an toàn rồi.",
        "Em xin theo kèo này với mọi người. Cùng nhau húp đậm nào!",
        "Vừa được học thêm một mẹo soi cầu mới từ anh C, kiến thức này quý giá quá.",
        "Em luôn ghi chép lại lời khuyên của các cao nhân. Đây là bí kíp làm giàu của em."
    ]
}