# file: kịch_bản/kho_kich_ban_me_bim.py

SCENARIOS_NOI_TRO_VY = {
    "morning": [
        "Chào buổi sáng cả nhà, em vừa cho con ăn xong, giờ mới có thời gian vào hóng hớt đây. Mọi người sao rồi ạ?",
        "Ở nhà lâu ngày đôi khi cũng tù túng, nhưng từ khi vào nhóm em lại thấy mình năng động, nhạy bén hơn hẳn.",
        "Em bắt đầu ngày mới bằng việc kiếm một khoản nhỏ. Nó không chỉ là tiền mà còn là sự tự tin đó mọi người.",
        "Hôm qua thắng được một ít, sáng nay em tự tin ra siêu thị mua thêm đồ ăn ngon cho cả nhà. Vui lắm ạ.",
        "Chồng em vừa đi làm là em phải vào nhóm ngay. Đây là không gian riêng để em 'sạc pin' đó.",
        "Em không muốn chỉ quanh quẩn việc nhà đâu, và nhóm đang giúp em chứng minh là mình vẫn làm được nhiều thứ.",
        "Chào các chị em, nhìn những con số nhảy múa làm em cảm thấy đầu óc mình linh hoạt hơn hẳn.",
        "Một lệnh win buổi sáng giúp em có thêm động lực dọn dẹp nhà cửa trong vui vẻ. Nay có gì hot không ạ?",
        "Em đang pha ấm trà, vừa nhâm nhi vừa theo dõi nhóm. Có chị em nào giống em không?",
        "Trước đây em chỉ lướt mấy trang mua sắm, giờ thì lướt nhóm để kiếm tiền. Cảm giác khác hẳn.",
        "Có thêm một khoản thu nhập giúp em thấy tự tin hơn hẳn trong các quyết định của gia đình.",
        "Em đang lên thực đơn cho cả tuần, thắng được tay nào là có thêm món ngon cho cả nhà. Hihi.",
        "Việc nhà không tên cứ quấn lấy mình, nhưng em luôn cố dành ra một khoảng thời gian cho 'công việc' này.",
        "Em xem đây là một cách đầu tư vào bản thân, vừa có tiền vừa rèn luyện trí não.",
        "Cảm giác tự mình kiếm tiền mua một món đồ mà không cần hỏi chồng nó tuyệt vời lắm các chị ạ.",
        "Chồng em chỉ nghĩ em đang tham gia một hội nhóm online cho vui thôi, anh ấy không biết nó lại 'hiệu quả' đến vậy.",
        "Hello cả nhà, em vừa dọn dẹp xong, giờ là lúc vào 'làm kinh tế' đây.",
        "Bắt đầu một ngày mới với sự chủ động và tích cực, em cảm ơn nhóm mình nhiều.",
        "Em không chỉ kiếm tiền, em đang tìm lại chính mình của những năm tháng còn đi làm.",
        "Một chiến thắng nhỏ thôi cũng đủ làm em vui cả ngày. Niềm vui của mẹ bỉm đôi khi đơn giản vậy."
    ],
    "noon": [
        "Nghỉ trưa rồi cả nhà ơi! Giờ này yên tĩnh là lúc em tập trung hóng kèo nhất.",
        "Em vừa tự thưởng cho mình ly trà sữa bằng tiền kiếm được. Cảm giác đã gì đâu.",
        "Sự tự chủ về tài chính, dù chỉ là một khoản nhỏ, cũng mang lại cho mình tiếng nói và sự tôn trọng.",
        "Em đang cố gắng kiếm thêm một khoản để cuối tuần tự tin đưa cả nhà đi ăn một bữa thịnh soạn.",
        "Cuộc sống của em bớt nhàm chán hơn hẳn từ khi có những giây phút hồi hộp này cùng mọi người.",
        "Thắng được một tay, coi như có thêm một khoản vào quỹ đen làm đẹp của mình rồi. Hehe.",
        "Chồng em không biết em có một 'công việc tay trái' thú vị và hiệu quả thế này đâu.",
        "Em tin rằng một người phụ nữ hạnh phúc là người vừa biết chăm lo gia đình, vừa biết tạo ra giá trị cho riêng mình.",
        "Em vừa tranh thủ đi chợ về, giờ là lúc vào xem thành quả của cả nhà mình. Sao rồi mọi người?",
        "Nhiều lúc bạn bè rủ đi cafe, trước đây em hay từ chối vì ngại xin tiền chồng, giờ thì tự tin đi luôn.",
        "Em đang xem dở bộ phim, nhưng một mắt vẫn phải liếc sang điện thoại theo dõi nhóm.",
        "Thắng kèo này là em có tiền đăng ký lớp học yoga rồi, phải đầu tư cho sức khỏe và vóc dáng.",
        "Em vừa gọi điện buôn chuyện với mẹ, vừa tranh thủ vào một lệnh. Phụ nữ mình siêu thật!",
        "Cảm giác tài khoản riêng của mình tăng lên mỗi ngày thật sự rất an toàn đó các chị.",
        "Em không cần phải kiếm quá nhiều, chỉ cần đủ để cảm thấy mình không phải là gánh nặng của ai cả.",
        "Lại một bữa trưa vui vẻ, cảm ơn các admin đã dẫn dắt.",
        "Em chuẩn bị đi đón con, chúc mọi người buổi chiều thắng lợi rực rỡ nhé.",
        "Em đang tập cho mình thói quen ghi chép lại chi tiêu từ nguồn thu này. Phải rõ ràng và chuyên nghiệp.",
        "Chồng em vừa nhắn tin hỏi trưa ăn gì, em trả lời 'em ăn sơn hào hải vị' vì vừa thắng lớn. Haha.",
        "Thắng rồi! Em phải đi nấu cơm trong niềm hân hoan mới được. Chúc cả nhà ăn trưa ngon miệng."
    ],
    "evening": [
        "Cả nhà ngủ hết rồi, đây mới thực sự là lúc em được là chính mình. Có ai còn thức không ạ?",
        "Em thích cái cảm giác được vận dụng trí óc để phán đoán, nó thú vị hơn nhiều so với việc xem phim giải trí.",
        "Cả ngày chỉ quanh quẩn trong nhà, tối đến được giao lưu với mọi người làm em thấy cuộc sống nhiều màu sắc hơn.",
        "Đêm là lúc em có thể xem lại lịch sử và rút ra bài học. Em tin mình sẽ ngày càng tiến bộ hơn.",
        "Chốt sổ hôm nay và có thêm một khoản vào quỹ riêng. Niềm vui này thật khó để diễn tả.",
        "Em xin phép nghỉ ngơi để giữ gìn nhan sắc đây. Chúc cả nhà mình tiếp tục gặt hái thành công nhé.",
        "Em vừa bí mật dùng tiền lời hôm nay để đặt mua tặng chồng chiếc đồng hồ anh ấy thích từ lâu.",
        "Ở đây, em tìm lại được hình ảnh của mình ngày trước, một cô gái tự tin và độc lập.",
        "Em vừa đắp mặt nạ xong, giờ là lúc thư giãn và kiếm tiền làm đẹp cho bản thân. Phải yêu bản thân trước.",
        "Chồng em đang xem bóng đá, em thì có 'trận đấu' của riêng mình ở đây. Ai sẽ thắng lớn hơn đây?",
        "Trước đây giờ này em chỉ lướt facebook xem người ta khoe khoang, giờ thì em tự tạo ra thành quả để tự hào.",
        "Cảm giác hồi hộp chờ kết quả vào lúc nửa đêm nó có một sự hấp dẫn kỳ lạ, mọi người nhỉ?",
        "Hôm nay là ngày kỷ niệm của vợ chồng em, em đang tính kiếm một món quà bất ngờ cho anh ấy.",
        "Em không thức khuya được lâu, nên sẽ chắt chiu từng cơ hội. Có kèo nào chắc ăn không admin ơi?",
        "Lại một đêm mất ngủ vì vui, nhưng là một sự mất ngủ hoàn toàn xứng đáng. Chúc mừng cả nhà!",
        "Em đã hoàn thành mục tiêu của ngày hôm nay, giờ có thể yên tâm đi ngủ rồi. Cảm ơn mọi người.",
        "Cảm ơn cả nhà đã thức cùng em, chúc mọi người ngủ ngon và mơ đẹp nhé.",
        "Tài khoản của em hôm nay đã tăng trưởng một cách ấn tượng, tất cả là nhờ sự đoàn kết của nhóm.",
        "Em sẽ dùng tiền lời hôm nay để ngày mai đi spa thư giãn. Phụ nữ phải biết yêu thương bản thân.",
        "Thôi em đi ngủ đây, hẹn gặp lại cả nhà vào sáng mai với nhiều năng lượng hơn."
    ],
    "experience_motivation": [
        "Từ ngày có thêm thu nhập từ nhóm, em không còn phải đắn đo mỗi khi muốn mua một món đồ cho bản thân nữa.",
        "Điều em nhận được lớn nhất ở đây không phải là tiền, mà là sự tự tin và cảm giác mình vẫn còn giá trị.",
        "Cảm ơn mọi người đã tạo ra một môi trường mà ở đó một người nội trợ như em cũng có thể toả sáng.",
        "Em đang ấp ủ dự định dùng số vốn tích lũy được để kinh doanh online một mặt hàng em yêu thích.",
        "Em nhận ra rằng, khi mình tự chủ về tài chính, mình cũng sẽ nhận được sự tôn trọng nhiều hơn từ người khác.",
        "Nhóm không chỉ dạy em cách kiếm tiền, mà còn dạy em cách tin vào bản thân mình một lần nữa.",
        "Hôm nay em tự tin dùng tiền mình kiếm được để mua quà sinh nhật cho chồng, cảm giác thật sự khác biệt.",
        "Em không còn cảm thấy tự ti khi đi họp lớp hay gặp gỡ bạn bè cũ nữa.",
        "Việc có một 'quỹ đen' vững chắc giúp em cảm thấy an tâm hơn trước những rủi ro của cuộc sống.",
        "Chồng em dạo này hay khen em vui vẻ và năng động hơn, anh ấy không biết bí quyết nằm ở đây. Hihi.",
        "Em đã có thể tự mình biếu bố mẹ đẻ một khoản tiền tiêu vặt mà không cần hỏi ý kiến chồng.",
        "Đối với em, nhóm như một cánh cửa mở ra một thế giới mới, nơi em được là chính mình và được công nhận.",
        "Em đã chứng minh được rằng, phụ nữ dù ở vai trò nào cũng có thể tạo ra giá trị.",
        "Mỗi lần tài khoản 'ting ting', em lại có thêm động lực để làm tốt hơn vai trò làm vợ, làm mẹ.",
        "Em sẽ không bao giờ quên cảm giác lần đầu tiên rút được tiền lời về tài khoản, nó là một cột mốc đáng nhớ.",
        "Em đã học được cách quản lý thời gian hiệu quả hơn để cân bằng giữa gia đình và 'sự nghiệp' này.",
        "Cuộc sống của em bây giờ không còn tẻ nhạt, mỗi ngày đều là một sự chờ đợi và hy vọng.",
        "Em khoe với các chị em, đây là thành quả sau 2 tuần của em, một chiếc máy rửa bát để giải phóng sức lao động.",
        "Cảm ơn nhóm đã giúp em tìm lại sự tự tin và niềm vui trong cuộc sống.",
        "Em tin rằng, chỉ cần nỗ lực và học hỏi, bất kỳ ai trong chúng ta cũng có thể thành công ở đây."
    ],
    "interaction": [
        "Em không tiện theo dõi liên tục vì còn bận con nhỏ, có thông tin nào quan trọng admin ghim lại giúp em với ạ.",
        "Phân tích của admin rất sắc bén và dễ hiểu, ngay cả một người không chuyên như em cũng nắm bắt được.",
        "Chúc mừng chị X, chị em mình phải cho các anh thấy phụ nữ cũng rất giỏi trong lĩnh vực này. Cố lên!",
        "Em là người mới nên còn hơi nhát tay, mọi người cho em lời khuyên về cách đi vốn với ạ. Em cảm ơn.",
        "Em vừa bận cho con ăn nên lỡ mất kèo, nhưng thấy cả nhà thắng là em cũng vui chung rồi.",
        "Ở trong nhóm này em cảm thấy rất tích cực, ai cũng sẵn sàng chia sẻ và giúp đỡ nhau. Thích lắm ạ.",
        "Có chị em nào giống em không? Chúng ta có thể lập một nhóm nhỏ chia sẻ kinh nghiệm cân bằng gia đình và 'sự nghiệp' này.",
        "Tay này em tin tưởng theo admin và mọi người, chúng ta là một đội mà.",
        "Em phải ghi chép lại những kinh nghiệm này vào một cuốn sổ tay riêng mới được.",
        "Mọi người cho em hỏi một chút về thuật ngữ này được không ạ, em chưa hiểu rõ lắm.",
        "Tuyệt vời! Em lại có thêm một khoản vào quỹ riêng rồi, cảm ơn cả nhà nhiều.",
        "Em vừa vào lệnh xong là phải đi lo cho bé, phó thác hết niềm tin cho các anh chị.",
        "Nhìn mọi người thảo luận sôi nổi làm em học hỏi được rất nhiều điều.",
        "Cảm ơn anh B đã chia sẻ kinh nghiệm quản lý cảm xúc, em thấy rất hữu ích.",
        "Em thấy phương pháp của nhóm mình rất khoa học, không phải kiểu may rủi nên rất yên tâm.",
        "Lại một ngày bội thu của cả nhà, chúc mừng chúng ta.",
        "Em có một thắc mắc nhỏ, không biết có tiện hỏi ở đây không ạ?",
        "Thắng lớn rồi! Em phải đi khoe với chồng mới được, cho anh ấy bất ngờ. Hihi.",
        "Em sẽ luôn đồng hành cùng nhóm, vì ở đây em tìm thấy quá nhiều giá trị.",
        "Cảm ơn mọi người đã luôn chào đón và động viên một thành viên mới như em."
    ]
}